trigger:
  batch: true
  branches:
    include: 
    - master
  paths:
    include:
    - demo-ignite2019-terraform/azure-pipelines-final.yml
    - demo-ignite2019-terraform/templates/*
        
stages:
- stage: Demo
  jobs:
  - template: templates/test.yml

- stage: Build
  jobs:
  - template: templates/build.yml

- stage: Staging
  jobs:
  - template: templates/release.yml
    parameters:
      environment: staging
      azureSubscription: $(stagingAzureSubscription)
      terraformStorageAccountName: mtcdenterraformsandbox

- stage: Production
  jobs:
  - template: templates/release.yml
    parameters:
      environment: production
      azureSubscription: $(productionAzureSubscription)
      terraformStorageAccountName: mtcdenterraformsandbox
