trigger:
  batch: true
  branches:
    include: 
    - master
  paths:
    include:
    - demo-ignite2019-terraform/azure-pipelines-terraform.yml

stages:
     
# Staging release
- stage: Staging
  jobs:
  - job: Release
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:

    # Download the published application artifact
    - download: current
      artifact: app

    # Release the app
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(stagingAzureSubscription)
        appType: 'webAppLinux'
        WebAppName: $(stagingAppName)
        packageForLinux: '$(System.DefaultWorkingDirectory)/*'
        RuntimeStack: 'DOTNETCORE|2.2'
        StartupCommand: 'dotnet run demo-app.dll'

# Production release  
- stage: Production
  jobs:
  - job: Release
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:

    # Download the published application artifact
    - download: current
      artifact: app
    
    # Release the app
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(productionAzureSubscription)
        appType: 'webAppLinux'
        WebAppName: ''
        packageForLinux: '$(System.DefaultWorkingDirectory)/*'
        RuntimeStack: 'DOTNETCORE|2.2'
        StartupCommand: 'dotnet run demo-app.dll'
