trigger:
  batch: true
  branches:
    include: 
    - master
  paths:
    include:
    - demo-ignite2019-terraform/azure-pipelines-app.yml

stages:

# Build Stage
- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    # Build and publish the application library
    - script: |
        set -e -x
        dotnet publish ./demo-ignite2019-terraform/src/demo-app.csproj -c release -o $(Build.StagingDirectory)
      displayName: Publish application

    # Publish the app as an artifact
    - publish: $(Build.StagingDirectory)
      artifact: app
        
      
# Staging release
- stage: Staging
  jobs:
  - job: Release
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    # Don't clone the repo
    - checkout: none

    # Download the published application artifact
    - download: current
      artifact: app

    # Release the app
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MTC Denver Sandbox'
        appType: 'webAppLinux'
        WebAppName:  jl-ignite2019-terraform-demo-staging-app
        packageForLinux: '$(Pipeline.Workspace)/app/*'
        RuntimeStack: 'DOTNETCORE|2.2'
        StartupCommand: 'dotnet run demo-app.dll'

# Production release  
- stage: Production
  jobs:
  - job: Release
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    
    # Don't clone the repo
    - checkout: none

    # Download the published application artifact
    - download: current
      artifact: app
    
    # Release the app
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MTC Denver Sandbox'
        appType: 'webAppLinux'
        WebAppName:  jl-ignite2019-terraform-demo-staging-app
        packageForLinux: '$(Pipeline.Workspace)/app/*'
        RuntimeStack: 'DOTNETCORE|2.2'
        StartupCommand: 'dotnet run demo-app.dll'