jobs:
- job: Deploy
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    # Build and publish the application library
    - script: |
        set -e -x
        dotnet publish ./demo-ignite2019-terraform/src/demo-app.csproj -c release -o $(Build.StagingDirectory)
      displayName: Publish application

    # Publish the app as an artifact
    - publish: $(Build.StagingDirectory)
      artifact: app