jobs:
# Validates a valid template
- job: CLI
  displayName: Test CLI
  dependsOn:
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: terraformInstaller@0
    inputs:
      terraformVersion: '0.12.13'
  
  - task: terraform@0
    inputs:
      command: 'CLI'
      providerAzureConnectedServiceName: 'MTC Denver Sandbox'
      backendAzureProviderStorageAccountName: 'mtcdenterraformsandbox'
      backendAzureStateFileKey: 'tfclitest.tfstate'
      cwd: $(System.DefaultWorkingDirectory)/demo-ignite2019-terraform/oldtf
      script: |
        # Validate
        terraform validate

        # Plan
        terraform plan -input=false -out=testplan.tf

    displayName: Run Terraform CLI

